### ISSUE TITLE
It takes a long time to start the program example_face_recognition_tflite.py

### ISSUE THREAD

**Issue by thile732** [nxp-imx/nxp-nnstreamer-examples#1]
I have a question, please answer if you have time. When I run the program example_face_detection_tflite.py on imx8m plus, it works immediately (face can be detected), but when I run the program example_face_recognition_tflite.py, after the image obtained from the camera shows up monitor, it takes about 2 minutes for the program to start displaying the results (name or unknown) on the monitor. What affected this delay?

**Comment by jvuillaumier** [comment]
Running example_face_recognition_tflite.py on  i.MX8M Plus platform on top of Linux 6.1.1_1.0.0 release, it takes ~40sec to have the first detection results displayed.
This delay on i.MX8M Plus comes from the warmup of the FaceNet512 model running on the NPU, corresponding to the time for its OpenVX graph compilation.

On i.MX8M Plus there is the option, using dedicated environment variables, to store the the result of the graph compilation in a file so that subsequent executions will start instantly.
You can refer to [i.MX Machine Learning User Guide](https://www.nxp.com/docs/en/user-guide/IMX-MACHINE-LEARNING-UG.pdf) section 9.1.3 'Hardware accelerators warmup time' for the details on how to enable this cache.

**Comment by jvuillaumier** [comment]
(Closing issue)
